//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TCMON.rc
//
#define IDS_NOPROVIDER                  1
#define IDC_STATUS                      102
#define IDD_TCMON_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDC_HOLD                        1000
#define IDC_UNHOLD                      1001
#define IDC_CALLLIST                    1002
#define IDC_LINEADDR                    1003
#define IDC_ANSWER                      1007
#define IDC_ACCEPT                      1008
#define IDC_OPEN                        1009
#define IDC_LINES                       1011
#define IDC_DROP                        1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
