//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RouteTest.rc
//
#define IDD_ROUTETEST_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDC_ROUTEPOINTS                 1000
#define IDC_NUMBER                      1001
#define IDC_RPLIST                      1002
#define IDC_ADD                         1003
#define IDC_REMOVE                      1004
#define IDC_LOG                         1005
#define IDC_CLEAR                       1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
