//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EnumTAPI.rc
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_DIALER_FORM                 101
#define IDD_ENUMTAPI_FORM               102
#define IDC_DEVICES                     1001
#define IDC_CONFIGURE                   1002
#define IDC_ADDRESSLIST                 1004
#define IDC_CALL                        1006
#define IDC_SERVICELIST                 1007
#define IDC_CAPS                        1008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
