// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#define TAPI_CURRENT_VERSION 0x00030001
#define WINVER 0x400
#define STRICT

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions (including VB)
#include <afxcmn.h>			// MFC Common controls (Win32)
#include <afxmt.h>			// MFC Threading support (Win32)
#include <tapi.h>           // TAPI support headers
#include "atapi.h"          // Applications library