//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Agent.rc
//
#define IDD_AGENT_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_ADDAGENT                    129
#define IDD_SETAGENTGROUP               130
#define IDD_SETAGENTSTATE               131
#define IDD_AGENTSTATUS                 132
#define IDC_AGENTS                      1000
#define IDC_ADD                         1001
#define IDC_STATE                       1001
#define IDC_REMOVE                      1002
#define IDC_AGENTLIST                   1002
#define IDC_SETAGENTSTATE               1003
#define IDC_NEXTSTATE                   1003
#define IDC_SETAGENTGROUP               1004
#define IDC_GROUPLIST                   1004
#define IDC_SETAGENTACTIVITY            1005
#define IDC_GROUP                       1005
#define IDC_CURRSTATE                   1006
#define IDC_CURRNEXTSTATE               1007
#define IDC_ADDRESS                     1007
#define IDC_GROUPS                      1008
#define IDC_ACTIVITY                    1010
#define IDC_RELOAD                      1011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
